### ISSUE TITLE
Question: Should the 'store' be a separate module?

### ISSUE THREAD

**Issue by james-gardner** [tomkis1/flux-boilerplate#5]
Hi,

Have I missed the point entirely or in the real world might we put the single/high-level store in it's own module? Where I've got unstuck with all this is that we have a store (at least conceptually) that houses application state. What if more than one component needs to make use of it? In the example it sits in TodoList.js - is this just for the purpose of the example?

Any clarification appreciated!

**Comment by james-gardner** [comment]
I think I needed to ask that seemingly silly question to come to my own conclusion. We'll always have a root component and that's why it's here.

**Comment by tomkis** [comment]
@james-gardner hey, this repo served just as supplementary repo to [this article](http://blog.javascripting.com/2015/06/19/flux-no-more-stores-meet-reducer/), it's pretty outdated, check out  something newer like [redux](https://github.com/reactjs/redux).
